AWSTemplateFormatVersion: '2010-09-09'
  
Parameters:
  KeyName:
    Description: Name of an existing EC2 KeyPair to enable SSH access to the instance
    Type: String
    Default: Putty-Test
  InstanceType:
    Description: WebServer EC2 instance type
    Type: String
    Default: t2.micro
  AMI:
    Type: String
  SG:
    Description: SecurityGroup
    Type: List<AWS::EC2::SecurityGroup::Id>
    Default: sg-06dfac953e6fe319e
Resources:
  EC2Instance:
    Type: AWS::EC2::Instance
    Properties:
      InstanceType: !Ref 'InstanceType'
      SecurityGroupIds: !Ref 'SG'
      KeyName: !Ref 'KeyName'
      ImageId: !Ref 'AMI'
  
Outputs:
  InstanceId:
    Description: InstanceId of the newly created EC2 instance
    Value: !Ref 'EC2Instance'
  AZ:
    Description: Availability Zone of the newly created EC2 instance
    Value: !GetAtt [EC2Instance, AvailabilityZone]
  
